#!/bin/sh /etc/rc.common
# "new(er)" style init script
 
START=80
APP=jackd
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1
 
start() {
        service_start /usr/bin/jackd -R -dalsa
}
 
stop() {
        service_stop /usr/bin/$APP
}